### ISSUE TITLE
Top cut off in Firefox/Chrome when screen width greater than 750px

### ISSUE THREAD

**Issue by colinbashbash** [duracellko/planningpoker4azure#1]
Top cut off in Firefox/Chrome when screen width greater than 750px

![responsive header](https://cloud.githubusercontent.com/assets/218669/6358618/86d883d4-bc32-11e4-9f55-258f974f99a2.png)

**Comment by duracellko** [comment]
Thank you for reporting. I need to do some more testing.

**Comment by duracellko** [comment]
Fixed in 96ee3492263a68d63d5f198670b51046fdfb5fc9

**Comment by duracellko** [comment]
Fix deployed
