### ISSUE TITLE
Scrum team does not exist

### ISSUE THREAD

**Issue by ewerton-ramos** [duracellko/planningpoker4azure#108]
Hi, I've been using the tool for some time, but in the last two weeks some colleagues are not able to join the estimation rooms.

I'm creating the room from Germany and the teammates from India see the following error when joining:
![error](https://user-images.githubusercontent.com/92453043/192502206-c8c24e88-0490-4b7c-8ff1-b1789e22c9ff.png)

The same issue happen to me when they create the room from India.

Do you know what could cause this?

**Comment by duracellko** [comment]
Hi @ewerton-ramos, thank you for feedback. I restarted the app and it should work correctly now.

**Comment by duracellko** [comment]
It seems I do not receive notifications about such failures. I will check that.

**Comment by ewerton-ramos** [comment]
Works now, thank you!
