### ISSUE TITLE
I18n feature I want to contribute for translate strings to Spanish 

### ISSUE THREAD

**Issue by johnfelipe** [duracellko/planningpoker4azure#124]

**Comment by duracellko** [comment]
Thank you very much for your will to contribute with a translation. I have to add proper support for I18n. I created task for that https://github.com/duracellko/planningpoker4azure/issues/125
When it is done, I will let you know.

**Comment by duracellko** [comment]
Hi @johnfelipe thank you very much for your will to contribute. What experience do you have with software translation? I suggest following options:

**Option 1**:
Clone the repository and copy files **UIResources.resx** to **UIResources.es.resx** in following directories:
- src\Duracellko.PlanningPoker.Client\UIResources.resx
- src\Duracellko.PlanningPoker.Web\UIResources.resx

You can open the files in Visual Studio. Or you can open it as XML file in any editor. And then translate all values from English to Spanish.
And then create Pull Request for review.

Note: There are also "Resources.resx" files, but they are just internal texts and do not have to be translated.
Note 2: There is translation to Slovak language. Maybe it helps to understand the structure.

**Option 2**:
I can prepare Excel file with all the application texts and send it to you. And you can send me Excel back with Spanish translations.

If you are familiar with any other tools, I am open for suggestions.

**Comment by johnfelipe** [comment]
Second option pls
When you send me excel file I will return string to Spanish
Tnks.

**Comment by duracellko** [comment]
Here is Excel with all the texts. There are 2 sheets (Client + Web). If you have any questions, let me know. Thank you very much.
[PlanningPoker-Translations.xlsx](https://github.com/duracellko/planningpoker4azure/files/11929946/PlanningPoker-Translations.xlsx)

**Comment by johnfelipe** [comment]
[PlanningPoker-Translations_spanish.xlsx](https://github.com/duracellko/planningpoker4azure/files/11951479/PlanningPoker-Translations_spanish.xlsx)
and
[PlanningPoker-Translations_italian.xlsx](https://github.com/duracellko/planningpoker4azure/files/11951480/PlanningPoker-Translations_italian.xlsx)

**Comment by duracellko** [comment]
Thank you very much for the translations into Spanish and Italian. I mentioned your contributions in https://github.com/duracellko/planningpoker4azure#attributions

I will deploy it on weekend.
