### ISSUE TITLE
Website does not appear to work with IOS browers

### ISSUE THREAD

**Issue by jvanhoof** [duracellko/planningpoker4azure#15]
When you access the website, even you own example one on the web, within IOS, none of the browsers will display the page, they get to the "loading" screen but never complete to the game screen.

Windows 10 Internet Explorer also has the same issue but not Chrome or Edge although I think that has recently started using the Chromium engine.

Thanks, great program, exactly what I wanted.

John

**Comment by duracellko** [comment]
Thank you very much for your feedback.

The application is implemented using [WebAssembly](https://webassembly.org/) technology that is supported by modern browsers only. Chrome, FireFox, Safari, Edge.
So unfortunately Internet Explorer is not supported. Also some alternative mobile browsers may have issues.

It is possible to switch server-side mode, and then wider range of browsers is supported. I will try to implement following things:
- Better test server-side mode. Situations like connection lost.
- Use server-side mode as fallback, when browser does not support webassembly. Currently it is application wide setting applied to all users.

**Comment by duracellko** [comment]
Application now falls back to server-side rendering on mobile and should work on iOS.
