### ISSUE TITLE
Problem with dotnet running the application 

### ISSUE THREAD

**Issue by kkoszarski** [duracellko/planningpoker4azure#52]
Hello @duracellko Rastislav  
The application works well running from the docker container as well as when it is being run from the visual studio. 
Problem appears when I try to build it using either attached powershell or debug/release configurations. While starting it everything looks green and normal with console output of\
`info: Microsoft.Hosting.Lifetime[0]
      Now listening on: http://localhost:5000
info: Microsoft.Hosting.Lifetime[0]
      Now listening on: https://localhost:5001
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Production
info: Microsoft.Hosting.Lifetime[0]`

But running the page ends up with 
>  Loading... 
> An error has occurred. This application may no longer respond until reloaded. 

If you have any immediate suggestion about debugging it or running it I would appreciate them.
best regards

**Comment by duracellko** [comment]
Thank you for the feedback.
Do you see any specific error, when you open Developer tools in browser and Console tab?

**Comment by kkoszarski** [comment]
> Thank you for the feedback.
> Do you see any specific error, when you open Developer tools in browser and Console tab?
Fair point - lots of missing files 
`GET http://localhost:5000/Content/Site.css net::ERR_ABORTED 404 (Not Found)
(index):52 GET http://localhost:5000/Scripts/PlanningPoker.js net::ERR_ABORTED 404 (Not Found)
(index):53 GET http://localhost:5000/_framework/blazor.webassembly.js net::ERR_ABORTED 404 (Not Found)
(index):52 GET http://localhost:5000/Scripts/PlanningPoker.js net::ERR_ABORTED 404 (Not Found)
(index):53 GET http://localhost:5000/_framework/blazor.webassembly.js net::ERR_ABORTED 404 (Not Found)`

**Comment by duracellko** [comment]
I think the application must be executed from current directory.

For example this does not work:
```
dotnet .\Build\web\Release\netcoreapp3.1\publish\Duracellko.PlanningPoker.Web.dll
```

but this should work:
```
cd .\Build\web\Release\netcoreapp3.1\publish
dotnet racellko.PlanningPoker.Web.dll
```

**Comment by kkoszarski** [comment]
> I think the application must be executed from current directory.
> 
> For example this does not work:
> 
> ```
> dotnet .\Build\web\Release\netcoreapp3.1\publish\Duracellko.PlanningPoker.Web.dll
> ```
> 
> but this should work:
> 
> ```
> cd .\Build\web\Release\netcoreapp3.1\publish
> dotnet racellko.PlanningPoker.Web.dll
> ```

You gave a hint with the path - it required a publish not only a build.
As I published the application to catalogue "Build\web\Release\netcoreapp3.1\publish" this made sense.
Still left doker part.
Anyways thank you for a great comprehensive project, help and fast response!
